# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarkProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
pod 'AFNetworking', '~> 4.0'
pod 'FMDB'
pod 'SDWebImage', '~> 5.0'
pod 'YYText'
pod 'YYCategories'
pod 'SDCycleScrollView','>= 1.80'
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
pod 'MBProgressHUD', '~> 1.2.0'
  # Pods for MarkProject

end
